In [1]:
import numpy as np

In [7]:
# 标量
s = 5

# 向量
v = np.array([1, 2])

# 矩阵
m = np.array([[1, 2], [3, 4]])

# 张量
t = np.array(
    [
      [[1, 2, 3], [4, 5, 6], [7, 8, 9]],
      [[11, 12, 13], [14, 15, 16], [17, 18,19]],
      [[21, 22, 23], [24, 25, 26], [27, 28,29]]
    ]
)

print('标量：', s)
print('向量：', v)
print('矩阵：\n', m)
print('张量：\n', t)

标量： 5
向量： [1 2]
矩阵：
 [[1 2]
 [3 4]]
张量：
 [[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[11 12 13]
  [14 15 16]
  [17 18 19]]

 [[21 22 23]
  [24 25 26]
  [27 28 29]]]


In [10]:
# 矩阵转置
A = np.array([[1.0, 2.0], [1.0, 0.0], [2.0, 3.0]])
A_t = A.T
print('A:\n', A)
print('A的转置:\n', A_t)

A:
 [[1. 2.]
 [1. 0.]
 [2. 3.]]
A的转置:
 [[1. 1. 2.]
 [2. 0. 3.]]


In [12]:
# 矩阵加法
a = np.array([[1.0, 2.0], [3.0, 4.0]])
b = np.array([[6.0, 7.0], [8.0, 9.0]])
print('矩阵相加：\n', a + b)

矩阵相加：
 [[ 7.  9.]
 [11. 13.]]


In [13]:
# 矩阵乘法
m1 = np.array([[1.0, 3.0], [1.0, 0.0]])
m2 = np.array([[1.0, 2.0], [5.0, 0.0]])

print('按矩阵乘法规则：\n', np.dot(m1, m2))
print('按逐元素相乘：\n', np.multiply(m1, m2))
print('按逐元素相乘：\n', m1 * m2)

v1 = np.array([1.0, 2.0])
v2 = np.array([4.0, 5.0])

print('向量内积：', np.dot(v1, v2))

按矩阵乘法规则：
 [[16.  2.]
 [ 1.  2.]]
按逐元素相乘：
 [[1. 6.]
 [5. 0.]]
按逐元素相乘：
 [[1. 6.]
 [5. 0.]]
向量内积： 14.0


In [14]:
# 单位矩阵
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [15]:
# 矩阵的逆
A = [[1.0, 2.0], [3.0, 4.0]]
A_inv = np.linalg.inv(A)
print('A 的逆矩阵\n', A_inv)

A 的逆矩阵
 [[-2.   1. ]
 [ 1.5 -0.5]]


In [16]:
# 范数
a = np.array([1.0, 3.0])
print('向量 L2 范数：', np.linalg.norm(a, ord=2))
print('向量 L1 范数：', np.linalg.norm(a, ord=1))
print('向量无穷范数：', np.linalg.norm(a, ord=np.inf))

向量 L2 范数： 3.1622776601683795
向量 L1 范数： 4.0
向量无穷范数： 3.0


In [17]:
a = np.array([[1.0,3.0],[2.0,1.0]])
print("矩阵 F 范数", np.linalg.norm(a, ord="fro"))

矩阵 F 范数 3.872983346207417


In [22]:
# 特征值分解
A = np.array([
    [1.0, 2.0, 3.0],
    [4.0, 5.0, 6.0],
    [7.0, 8.0, 9.0]
])

# 计算特征值
print('特征值：', np.linalg.eigvals(A))

# 计算特征向量和特征值
eigvals, eigvectors = np.linalg.eig(A)
print('特征值：', eigvals)
print('特征向量：\n', eigvectors)

print('A：\n', eigvectors.dot(np.diag(eigvals)).dot(np.linalg.inv(eigvectors)))

特征值： [ 1.61168440e+01 -1.11684397e+00 -1.30367773e-15]
特征值： [ 1.61168440e+01 -1.11684397e+00 -1.30367773e-15]
特征向量：
 [[-0.23197069 -0.78583024  0.40824829]
 [-0.52532209 -0.08675134 -0.81649658]
 [-0.8186735   0.61232756  0.40824829]]
A：
 [[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]


In [26]:
# 奇异值分解
A = np.array(
    [
        [1.0, 2.0, 3.0],
        [4.0, 5.0, 6.0]
    ]
)

U, D, V = np.linalg.svd(A)

print("U:\n", U)
print("D:\n", D)
print("V:\n", V)

U:
 [[-0.3863177  -0.92236578]
 [-0.92236578  0.3863177 ]]
D:
 [9.508032   0.77286964]
V:
 [[-0.42866713 -0.56630692 -0.7039467 ]
 [ 0.80596391  0.11238241 -0.58119908]
 [ 0.40824829 -0.81649658  0.40824829]]
